/**
 * Core memory schema for ALBUDDY — the canonical contract binding memory
 * storage, the read/write API (ALB-7), and all future UI layers.
 *
 * Aligned with GOV-DAT-001 §2 (Memory Node Anatomy, Relationship Edge Anatomy).
 *
 * Phase 1 (MVP): Full node schema; edges stored but graph traversal deferred.
 * Phase 2: Full bidirectional graph traversal, active privacy-tier enforcement,
 *          automated decay/archival pipelines.
 *
 * @version 1.1.0
 * @see docs/architecture/memory-schema.md
 *
 * ## Changelog
 * - 1.1.0 — Bi-temporal validity (`validFrom`/`validTo`) so a superseded fact is
 *   invalidated, not deleted; the graph records how knowledge changed over time.
 *   Embeddings moved to a dedicated, model-tagged {@link MemoryEmbedding} side
 *   store (disposable, re-embeddable cache); inline `MemoryNode.embedding` is
 *   deprecated. Portability review (2026-07-07) — see
 *   docs/architecture/memory-architecture-decision.md.
 * - 1.0.0 — Canonical node/edge schema (ALB-2), aligned with GOV-DAT-001 §2.
 */

// ---------------------------------------------------------------------------
// Enums — GOV-DAT-001 §2
// ---------------------------------------------------------------------------

/**
 * GOV-DAT-001 §2.1 — Canonical memory node types.
 * `Narrative` supports long-form prose preservation summaries (§3.6).
 */
export type MemoryNodeType =
  | "Experience" // Episodic — something that happened
  | "Lesson" // Semantic — something learned
  | "Conversation" // Verbatim or summarized dialogue
  | "Belief" // Value, opinion, or conviction
  | "Relationship" // A person, group, or entity the user relates to
  | "Skill" // Procedural — something the user can do
  | "Narrative"; // Long-form prose preservation summary (§3.6)

/**
 * GOV-DAT-001 §2.1 — How a node entered the system.
 */
export type MemoryProvenance =
  | "UserInput" // Directly authored by the user
  | "AIInferred" // Derived/generated by the AI system
  | "GuardianAdded" // Added by a designated guardian (under-age accounts)
  | "SystemGenerated"; // Automated system operation (e.g., session summaries)

/**
 * GOV-DAT-001 §2.3 — Controls AI access and external sharing.
 *
 * Phase 1: field is required; classification is informational.
 * Phase 2: enforcement is active — Sealed nodes are excluded from AI context.
 */
export type PrivacyClassification =
  | "Public" // Shareable with user, AI, and designated advisors
  | "Private" // Default — accessible to user and AI only
  | "Sensitive" // Excluded from summarization unless user explicitly opts in
  | "Sealed"; // AI may not read, reference, or summarize

/**
 * GOV-DAT-001 §3.2 — Retention tier lifecycle.
 */
export type RetentionTier =
  | "FullRetention" // Stored in original form, fully indexed and searchable
  | "Summarized" // Raw content replaced by AI-generated narrative summary
  | "Archived" // Cold storage; excluded from active AI context by default
  | "PendingDeletion"; // 14-day grace period before irreversible destruction

// ---------------------------------------------------------------------------
// Memory Node — GOV-DAT-001 §2.1
// ---------------------------------------------------------------------------

/**
 * A timestamped event in a node's temporal lifecycle.
 * The `temporalAnchors` array is append-only — entries are never removed.
 */
export interface TemporalAnchor {
  timestamp: string; // ISO 8601
  event: "created" | "recalled" | "reinforced" | "modified" | "summarized" | "archived";
}

/**
 * Structured content payload. Phase 1 requires only `text`.
 * `structuredData` and `attachmentRefs` are reserved for Phase 2.
 */
export interface MemoryContent {
  text: string;
  structuredData?: Record<string, unknown>; // Phase 2: typed sub-fields per memoryType
  attachmentRefs?: string[]; // Phase 2: references to attached files/media
}

/**
 * GOV-DAT-001 §2.1 — A memory node in the ALBUDDY semantic graph.
 *
 * Immutable fields (`readonly`) must not change after creation.
 * All timestamps are ISO 8601 strings to remain JSON-serializable and LLM-agnostic.
 */
export interface MemoryNode {
  // --- Identity (immutable) ---
  readonly nodeId: string; // UUID v4 — stable across all storage layers
  readonly provenance: MemoryProvenance; // How this node entered the system
  readonly encryptionKeyRef: string; // Reference to the user-controlled encryption key

  // --- Classification ---
  memoryType: MemoryNodeType;
  privacyClassification: PrivacyClassification; // Default: "Private"
  retentionTier: RetentionTier; // Default: "FullRetention"

  // --- Content ---
  content: MemoryContent;
  contextualMetadata: Record<string, unknown>; // Tags, themes, user-added labels

  // --- Temporal: transaction time (§2.1 temporalAnchors — append-only) ---
  // WHEN THE SYSTEM recorded events about this node (created/recalled/modified…).
  temporalAnchors: TemporalAnchor[];

  // --- Temporal: valid time (bi-temporal, v1.1.0) ---
  // WHEN THE FACT IS TRUE IN THE WORLD, independent of when we recorded it.
  // A superseded fact is NOT deleted — it keeps its node and gets `validTo` set,
  // so the graph records how the user's life changed over time
  // (e.g. "lived in London" gets a validTo when they move to Tokyo).
  // The store defaults `validFrom` to creation time and `validTo` to null (open).
  validFrom: string; // ISO 8601 — when the fact became true.
  validTo: string | null; // ISO 8601, or null for open-ended / still true.

  // --- Confidence & Decay (§3.5) ---
  confidenceWeight: number; // Float [0.0–1.0] — estimated freshness/relevance
  decayRate: number; // Rate at which confidence degrades without reinforcement

  /**
   * @deprecated Since 1.1.0. Inline embeddings are frozen — vectors now live in
   * the dedicated {@link MemoryEmbedding} side store (see `setEmbedding`), tagged
   * with the model that produced them so they stay a disposable, re-embeddable
   * cache. Raw `content.text` remains the source of truth. Do not write this field.
   */
  embedding?: number[];
}

/**
 * Input to {@link MemoryStore.addNode}. The store assigns `nodeId` and the
 * initial `temporalAnchors`, and defaults valid-time when not supplied
 * (`validFrom` → creation time, `validTo` → null). Callers MAY still provide
 * valid-time explicitly for facts that were true before they were recorded
 * (e.g. "I moved to Tokyo in 2020").
 */
export type NewMemoryNode = Omit<
  MemoryNode,
  "nodeId" | "temporalAnchors" | "validFrom" | "validTo"
> & {
  validFrom?: string;
  validTo?: string | null;
};

// ---------------------------------------------------------------------------
// Relationship Edge — GOV-DAT-001 §2.2
// ---------------------------------------------------------------------------

/**
 * GOV-DAT-001 §2.2 — Typed relationship between two memory nodes.
 */
export type RelationshipType =
  | "Cause" // A caused B
  | "Analogy" // A is analogous to B
  | "Reinforcement" // A strengthens or confirms B
  | "Contradiction" // A conflicts with B
  | "Temporal" // A precedes or follows B chronologically
  | "Emotional" // A has an emotional connection to B
  | "Conceptual"; // A and B share a conceptual theme

/** Who asserted a relationship edge. */
export type EdgeProvenance = "UserAsserted" | "AIInferred";

/**
 * GOV-DAT-001 §2.2 — A typed directed edge in the memory graph.
 *
 * Phase 1: Edges may be persisted but graph traversal is not required by the API.
 * Phase 2: Full bidirectional traversal is a first-class API capability.
 */
export interface MemoryEdge {
  readonly edgeId: string; // UUID v4, immutable
  readonly sourceNodeId: string; // Origin node
  readonly targetNodeId: string; // Destination node
  readonly createdAt: string; // ISO 8601

  relationshipType: RelationshipType;
  strength: number; // Float [0.0–1.0] — confidence in the relationship
  provenance: EdgeProvenance;
}

// ---------------------------------------------------------------------------
// Embeddings — model-tagged vector cache (v1.1.0)
// ---------------------------------------------------------------------------

/** Distance metric a vector index compares embeddings with. */
export type EmbeddingMetric = "cosine" | "dot" | "euclidean";

/**
 * A vector embedding of a node's content, kept in a dedicated side store keyed
 * by `(nodeId, model)`.
 *
 * Embeddings are a **disposable, re-embeddable cache** — `MemoryNode.content.text`
 * is always the source of truth. Every vector is tagged with the model that
 * produced it, so upgrading to a better embedding model is a re-index, not a
 * data-loss migration. Vectors from different models are never comparable, so
 * they coexist per-model rather than overwriting each other.
 */
export interface MemoryEmbedding {
  readonly nodeId: string; // FK → MemoryNode.nodeId
  readonly model: string; // e.g. "voyage-3-large", "text-embedding-3-large"
  readonly modelVersion: string; // Provider's version tag for reproducibility
  readonly dimensions: number; // Length of `vector`
  readonly metric: EmbeddingMetric;
  vector: number[];
  readonly createdAt: string; // ISO 8601 — store-assigned
}

// ---------------------------------------------------------------------------
// Query & Store interfaces
// ---------------------------------------------------------------------------

export interface MemoryQueryOptions {
  memoryType?: MemoryNodeType | MemoryNodeType[];
  privacyClassification?: PrivacyClassification[];
  retentionTier?: RetentionTier[];
  tags?: string[];
  minConfidence?: number;
  query?: string; // Semantic / full-text search string
  /**
   * Bi-temporal filter: return only nodes whose valid-time window contains this
   * instant — `validFrom <= validAt AND (validTo IS NULL OR validTo > validAt)`.
   * Omit to ignore valid-time (returns nodes regardless of whether superseded).
   */
  validAt?: string; // ISO 8601
  limit?: number;
  after?: string; // Cursor-based pagination (nodeId)
}

/**
 * Storage-agnostic interface for the memory graph.
 * Implementations may be local SQLite, Neptune, Neo4j, or an in-memory store —
 * the API surface does not change.
 */
export interface MemoryStore {
  // Node operations
  addNode(node: NewMemoryNode): Promise<MemoryNode>;
  getNode(nodeId: string): Promise<MemoryNode | undefined>;
  searchNodes(options: MemoryQueryOptions): Promise<MemoryNode[]>;
  updateNode(
    nodeId: string,
    patch: Partial<
      Pick<
        MemoryNode,
        | "content"
        | "contextualMetadata"
        | "confidenceWeight"
        | "decayRate"
        | "privacyClassification"
        | "retentionTier"
        | "memoryType"
        // Valid-time: set `validTo` to invalidate (supersede) a fact without
        // deleting it; correct `validFrom` if the real-world start was wrong.
        | "validFrom"
        | "validTo"
      >
    >,
    /** Lifecycle event to record on the appended anchor. Default "modified";
     *  pass "reinforced" when a duplicate observation strengthens the node. */
    anchorEvent?: TemporalAnchor["event"],
  ): Promise<MemoryNode>;
  deleteNode(nodeId: string): Promise<void>;

  // Portability — verbatim restore for round-trip import (nodeId, anchors,
  // and valid-time preserved exactly; never generates new identity).
  restoreNode(node: MemoryNode): Promise<void>;
  restoreEdge(edge: MemoryEdge): Promise<void>;

  // Edge operations (Phase 1: store/retrieve; Phase 2: full traversal)
  addEdge(edge: Omit<MemoryEdge, "edgeId" | "createdAt">): Promise<MemoryEdge>;
  getEdges(nodeId: string): Promise<MemoryEdge[]>;
  deleteEdge(edgeId: string): Promise<void>;

  // Embedding operations — a disposable, model-tagged vector cache (v1.1.0).
  /** Upsert the embedding for `(nodeId, model)`. Re-embedding with the same
   *  model replaces the vector; a different model coexists alongside it. */
  setEmbedding(embedding: Omit<MemoryEmbedding, "createdAt">): Promise<MemoryEmbedding>;
  /** All embeddings held for a node, one per model. */
  getEmbeddings(nodeId: string): Promise<MemoryEmbedding[]>;
  /** All embeddings for one model across the whole store (vector-scan input). */
  listEmbeddings(model: string): Promise<MemoryEmbedding[]>;
  /** Drop a node's embeddings — all of them, or just one model's. */
  deleteEmbeddings(nodeId: string, model?: string): Promise<void>;
}

// ---------------------------------------------------------------------------
// Legacy — remove once ALB-7 ships
// ---------------------------------------------------------------------------

/** @deprecated Use MemoryNodeType. Retained for transition only. */
export type MemoryType = "episodic" | "semantic" | "procedural";

/** @deprecated Use MemoryNode. Will be removed when ALB-7 ships. */
export interface MemoryEntry {
  id: string;
  type: MemoryType;
  content: string;
  embedding?: number[];
  tags: string[];
  importance: number;
  createdAt: Date;
  lastAccessedAt: Date;
  accessCount: number;
  metadata: Record<string, unknown>;
}
